In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('C:/Users/ASIA_08/petition.csv')

In [4]:
df.shape

(395547, 8)

In [13]:
df.head(5)

,article_id,start,end,answered,votes,category,title,content
0,21,2017-08-19,2017-11-17,0,9,안전/환경,스텔라 데이지호에 대한 제안입니다.,스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가...
1,22,2017-08-19,2017-11-17,0,17,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...
2,23,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ..."
3,24,2017-08-19,2017-08-26,0,53,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...
4,25,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ..."

In [12]:
df.tail(3)

,article_id,start,end,answered,votes,category,title,content
395544,517120,2019-02-04,2019-03-06,0,0,안전/환경,환경문제,명절이면 후로 제일문제는 쓰레기 문제 입니다.\n제일문제는 선물세트와 농산물세트 입...
395545,517121,2019-02-04,2019-03-06,0,20,정치개혁,"청화대,더불어민주당, 당장 답하라,,,,,,","좌파 더불어민주당, 좌파 정권 청화대는 선한 국민들을 더는 기망하지 말고 담장 답하..."
395546,517122,2019-02-04,2019-03-06,0,16,인권/성평등,여성부 폐지,국민들이 원합니다\n폐지 좀 시키세요;

In [10]:
df.info()#컬럼 이름, 설명

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395547 entries, 0 to 395546
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   article_id  395547 non-null  int64
 1   start       395547 non-null  object
 2   end         395547 non-null  object
 3   answered    395547 non-null  int64
 4   votes       395547 non-null  int64
 5   category    395547 non-null  object
 6   title       395547 non-null  object
 7   content     395546 non-null  object
dtypes: int64(3), object(5)
memory usage: 24.1+ MB

In [11]:
df.isnull().sum()

article_id    0
start         0
end           0
answered      0
votes         0
category      0
title         0
content       1
dtype: int64

In [22]:
df.columns

Index(['article_id', 'start', 'end', 'answered', 'votes', 'category', 'title',
       'content'],
      dtype='object')

In [26]:
df.dtypes

article_id     int64
start         object
end           object
answered       int64
votes          int64
category      object
title         object
content       object
dtype: object

In [27]:
df.describe()[['answered','votes']]

            answered         votes
count  395547.000000  3.955470e+05
mean        0.000073  1.501188e+02
std         0.008562  4.802583e+03
min         0.000000  0.000000e+00
25%         0.000000  2.000000e+00
50%         0.000000  5.000000e+00
75%         0.000000  1.500000e+01
max         1.000000  1.192049e+06

In [33]:
pd.options.display.float_format = '{:.2f}'.format
df.describe()[['answered','votes']]

       answered      votes
count 395547.00  395547.00
mean       0.00     150.12
std        0.01    4802.58
min        0.00       0.00
25%        0.00       2.00
50%        0.00       5.00
75%        0.00      15.00
max        1.00 1192049.00

In [32]:
pd.set_option('float.format','{:f}'.format)

In [34]:
#카테고리형만 모으기
df.describe(include=np.object)

             start         end category     title   content
count       395547      395547   395547    395547    395546
unique         535         558       17    346524    375224
top     2017-11-11  2017-12-11     정치개혁  이명박 출국금지  이명박 출국금지
freq          9623        9701    62750      3018       597

In [58]:
#20만건 이상 답변대상 청원 보기
df_20=[]
for i in df['votes']:
    if i>200000:
        df_20=df_20.append(i)

AttributeError: 'NoneType' object has no attribute 'append'

In [65]:
df_20=df[df['votes']>200000]

In [69]:
df_20.shape

(80, 8)

In [70]:
df_10=df[df['votes']>1000]
df_10.shape

(3472, 8)

In [71]:
df['votes']>1000

0         False
1         False
2         False
3         False
4         False
          ...
395542    False
395543    False
395544    False
395545    False
395546    False
Name: votes, Length: 395547, dtype: bool

In [72]:
df_20.

,article_id,start,end,answered,votes,category,title,content
1752,1785,2017-09-03,2017-11-02,1,296330,인권/성평등,청소년이란 이유로 보호법을 악용하는 잔인무도한 청소년들이 늘어나고있습니다. 반드시 ...,안녕하십니까. 청소년보호법이란 명목하에 나쁜짓을 일삼는 청소년들이 너무나 많아지고 ...
10894,10949,2017-09-06,2017-12-05,1,615354,미래,조두순 출소반대,제발 조두순 재심다시해서 무기징역으로 해야됩니다!!!
18111,18278,2017-09-30,2017-10-30,1,235372,인권/성평등,낙태죄 폐지와 자연유산 유도약(미프진) 합법화 및 도입을 부탁드립니다.,안녕하세요. 존경하는 대통령님 의원님\n낙태죄 폐지를 청원합니다.\n현재 대한민국은...
25032,26024,2017-11-04,2017-12-04,1,216774,안전/환경,'주취감형(술을 먹으면 형벌 감형)' 폐지를 건의(청원)합니다.,"'주취감형'이란, 술을 먹고 범행을 저지를 때, 심신미약 (이성이 없고 우발적)이라..."
43992,45581,2017-11-17,2017-12-17,1,281985,보건복지,"권역외상센터 (이국종 교수님) 추가적, 제도적, 환경적, 인력 지원","청원사항)\n중증외상분야의 추가적, 제도적, 환경적, 인력 지원 방안마련\n현 의료..."
...,...,...,...,...,...,...,...,...
363005,472309,2018-12-18,2019-01-17,0,269110,인권/성평등,조재범 코치를 강력처벌해주세요,그는 국가대표 심석희 외 다수의 여자선수들을 지속적으로 적어도 14년간 폭행해온 쓰...
375654,489302,2019-01-07,2019-02-06,0,302856,정치개혁,여.야는 속히 공수처 신설하라 !!!,지금 대한 민국은 나라를 바로 잡기 위해 반드시 이번 정부내에 검찰과 법원의 확실한...
390787,510422,2019-01-29,2019-02-28,0,312197,기타,"경사 ***, 경장 *** 외 ***에서 뇌물받는지 조사부탁드립니다.","경사 ***, 경장 *** 등등 ***에서 뇌물받는지 조사부탁드립니다.\nㅡㅡㅡㅡㅡ..."
391208,511075,2019-01-29,2019-02-28,0,207784,인권/성평등,"공공연한 여성 대상 약물 범죄 처벌과 ***을 비롯한 클럽, 유흥업소와 경찰 간의 ...",*** 사태의 핵심은 클럽&유흥업소 운영 관리인들의 의도적 약물 사용이 의심되는 납...
391984,512112,2019-01-30,2019-03-01,0,270999,정치개혁,"시민의 이름으로, 이번 김경수 지사 재판에 관련된 법원 판사 전원의 사퇴를 명령합니다.","촛불혁명으로 세운 정부와 달리, 사법부는 여전히 과거의 구습과 적폐적 습관을 버리지..."

In [82]:
df_20.category.value_counts()

인권/성평등         24
안전/환경          10
정치개혁            8
기타              8
문화/예술/체육/언론     7
반려동물            4
외교/통일/국방        4
보건복지            3
육아/교육           3
교통/건축/국토        3
경제민주화           2
성장동력            2
미래              1
행정              1
Name: category, dtype: int64

In [84]:
df_20['category'].value_counts()

인권/성평등         24
안전/환경          10
정치개혁            8
기타              8
문화/예술/체육/언론     7
반려동물            4
외교/통일/국방        4
보건복지            3
육아/교육           3
교통/건축/국토        3
경제민주화           2
성장동력            2
미래              1
행정              1
Name: category, dtype: int64

In [85]:
df_20['category']

1752      인권/성평등
10894         미래
18111     인권/성평등
25032      안전/환경
43992       보건복지
           ...
363005    인권/성평등
375654      정치개혁
390787        기타
391208    인권/성평등
391984      정치개혁
Name: category, Length: 80, dtype: object

In [89]:
df_20[['title','votes','content']]

,title,votes,content
1752,청소년이란 이유로 보호법을 악용하는 잔인무도한 청소년들이 늘어나고있습니다. 반드시 ...,296330,안녕하십니까. 청소년보호법이란 명목하에 나쁜짓을 일삼는 청소년들이 너무나 많아지고 ...
10894,조두순 출소반대,615354,제발 조두순 재심다시해서 무기징역으로 해야됩니다!!!
18111,낙태죄 폐지와 자연유산 유도약(미프진) 합법화 및 도입을 부탁드립니다.,235372,안녕하세요. 존경하는 대통령님 의원님\n낙태죄 폐지를 청원합니다.\n현재 대한민국은...
25032,'주취감형(술을 먹으면 형벌 감형)' 폐지를 건의(청원)합니다.,216774,"'주취감형'이란, 술을 먹고 범행을 저지를 때, 심신미약 (이성이 없고 우발적)이라..."
43992,"권역외상센터 (이국종 교수님) 추가적, 제도적, 환경적, 인력 지원",281985,"청원사항)\n중증외상분야의 추가적, 제도적, 환경적, 인력 지원 방안마련\n현 의료..."
...,...,...,...
363005,조재범 코치를 강력처벌해주세요,269110,그는 국가대표 심석희 외 다수의 여자선수들을 지속적으로 적어도 14년간 폭행해온 쓰...
375654,여.야는 속히 공수처 신설하라 !!!,302856,지금 대한 민국은 나라를 바로 잡기 위해 반드시 이번 정부내에 검찰과 법원의 확실한...
390787,"경사 ***, 경장 *** 외 ***에서 뇌물받는지 조사부탁드립니다.",312197,"경사 ***, 경장 *** 등등 ***에서 뇌물받는지 조사부탁드립니다.\nㅡㅡㅡㅡㅡ..."
391208,"공공연한 여성 대상 약물 범죄 처벌과 ***을 비롯한 클럽, 유흥업소와 경찰 간의 ...",207784,*** 사태의 핵심은 클럽&유흥업소 운영 관리인들의 의도적 약물 사용이 의심되는 납...
391984,"시민의 이름으로, 이번 김경수 지사 재판에 관련된 법원 판사 전원의 사퇴를 명령합니다.",270999,"촛불혁명으로 세운 정부와 달리, 사법부는 여전히 과거의 구습과 적폐적 습관을 버리지..."

In [115]:
df_high=df_20['votes'].sort_values(ascending=[False]).head(5)
df_high

313314    1192049
208597     714875
10894      615354
118970     614127
183791     419006
Name: votes, dtype: int64

In [153]:
df[df['votes']>20000]\
  .sort_values(by='votes',ascending=[False])\
  .head(5)

,article_id,start,end,answered,votes,category,title,content,answer
313314,408609,2018-10-17,2018-11-16,0,1192049,안전/환경,강서구 피시방 살인 사건. 또 심신미약 피의자입니다.,2018년 10월 14일 엊그제 일어난 강서구 피시방 살인사건에 대한 청원입니다.\...,True
208597,269548,2018-06-13,2018-07-13,0,714875,외교/통일/국방,"제주도 불법 난민 신청 문제에 따른 난민법, 무사증 입국, 난민신청허가 폐지/개헌 ...",2012년 난민법 제정으로 인해 외국인은 한달 무비자로 입국할 수 있으나 난민신청자...,True
10894,10949,2017-09-06,2017-12-05,1,615354,미래,조두순 출소반대,제발 조두순 재심다시해서 무기징역으로 해야됩니다!!!,True
118970,142600,2018-02-19,2018-03-21,1,614127,문화/예술/체육/언론,"김보름, 박지우 선수의 자격박탈과 적폐 빙상연맹의 엄중 처벌을 청원합니다","오늘 여자 단체전 팀추월에서 김보름, 박지우 선수는 팀전인데도 불구하고 개인의 영달...",True
183791,230552,2018-05-11,2018-06-10,1,419006,인권/성평등,여성도 대한민국 국민입니다. 성별 관계없는 국가의 보호를 요청합니다.,최근 홍대 누드크로키 모델의 불법촬영 사건이 있었습니다.\n사건은 굉장히 빠르게 처...,True

In [109]:
df_high

313314    1192049
208597     714875
10894      615354
118970     614127
183791     419006
Name: votes, dtype: int64

In [112]:
df.loc[row,:3]

NameError: name 'row' is not defined

In [121]:
df_20=df['votes']>200000

In [137]:
df['answer']=df_20
df

,article_id,start,end,answered,votes,category,title,content,answer
0,21,2017-08-19,2017-11-17,0,9,안전/환경,스텔라 데이지호에 대한 제안입니다.,스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가...,False
1,22,2017-08-19,2017-11-17,0,17,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...,False
2,23,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",False
3,24,2017-08-19,2017-08-26,0,53,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...,False
4,25,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",False
...,...,...,...,...,...,...,...,...,...
395542,517117,2019-02-04,2019-03-06,0,3,보건복지,명절연휴 고속도로 무료반대,명절고속도로 무료보단 대다수의 서민들이 이용하는 대중교통 무료와 명절기간 증차로 했...,False
395543,517119,2019-02-04,2019-03-06,0,23,보건복지,광주사태 가짜 유공자들 정수기로 걸려내야함,광주사태 유공자들 차고 넘치는데 이래 많은 유공자들 그냥놓아두면 재앙이다.\n김대중...,False
395544,517120,2019-02-04,2019-03-06,0,0,안전/환경,환경문제,명절이면 후로 제일문제는 쓰레기 문제 입니다.\n제일문제는 선물세트와 농산물세트 입...,False
395545,517121,2019-02-04,2019-03-06,0,20,정치개혁,"청화대,더불어민주당, 당장 답하라,,,,,,","좌파 더불어민주당, 좌파 정권 청화대는 선한 국민들을 더는 기망하지 말고 담장 답하...",False
395546,517122,2019-02-04,2019-03-06,0,16,인권/성평등,여성부 폐지,국민들이 원합니다\n폐지 좀 시키세요;,False

In [138]:
df.sort_values(by='answer',ascending=[False])

,article_id,start,end,answered,votes,category,title,content,answer
186976,235102,2018-05-17,2018-06-16,1,201590,인권/성평등,합정 **** 불법 누드촬영,한 유명 유튜버의 사례\n저는 성범죄 피해자입니다. 꼭 한번만 제 이야기를 들어주세...,True
112158,134590,2018-02-08,2018-03-10,1,207772,경제민주화,경제민주화,김상조 공정거래위원장이 경제정의 구현을 위한 정책들에 대해서 적극적인 지지를 보냅...,True
313314,408609,2018-10-17,2018-11-16,0,1192049,안전/환경,강서구 피시방 살인 사건. 또 심신미약 피의자입니다.,2018년 10월 14일 엊그제 일어난 강서구 피시방 살인사건에 대한 청원입니다.\...,True
43992,45581,2017-11-17,2017-12-17,1,281985,보건복지,"권역외상센터 (이국종 교수님) 추가적, 제도적, 환경적, 인력 지원","청원사항)\n중증외상분야의 추가적, 제도적, 환경적, 인력 지원 방안마련\n현 의료...",True
316569,412722,2018-10-20,2018-11-19,0,261418,인권/성평등,조두순의 출소를 반대합니다,제 얘기를 하기에 앞서 요즘 페이스북이라는 sns에서 화제가 되고 있는 글을 하나 ...,True
...,...,...,...,...,...,...,...,...,...
131856,157723,2018-03-04,2018-04-03,0,0,일자리,남양주 청소업체 비정규직 채용의 실태,남양주시 청소업체 비정규직에서 정규직으로 채용하는 과정이 너무 부당...,False
131855,157722,2018-03-04,2018-04-03,0,16,경제민주화,"이명박외 친일재산 환수에 관한 특별법 청원건과 삼성의 구릅의 해체에 관한건,",상기건을 청원합니다,False
131854,157721,2018-03-04,2018-04-03,0,2,일자리,중소기업 직장인들을 위해 개선대책 수립해주세요,중소기업에 다니고 있습니다\n아래 기사가 가슴에 와닿습니다 ㅠ\n수당없고 보너스없고...,False
131853,157720,2018-03-04,2018-04-03,0,14,보건복지,보건소장 의사 임명 금지해주세요,병원의 간호사 1인당 담당환자43명 뉴스\n이것은 보건소가 병원을 감독않고 손을 놓...,False
395546,517122,2019-02-04,2019-03-06,0,16,인권/성평등,여성부 폐지,국민들이 원합니다\n폐지 좀 시키세요;,False

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395547 entries, 0 to 395546
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   article_id  395547 non-null  int64
 1   start       395547 non-null  object
 2   end         395547 non-null  object
 3   answered    395547 non-null  int64
 4   votes       395547 non-null  int64
 5   category    395547 non-null  object
 6   title       395547 non-null  object
 7   content     395546 non-null  object
 8   answer      395547 non-null  bool
dtypes: bool(1), int64(3), object(5)
memory usage: 24.5+ MB

In [143]:
df1=df.copy()

In [144]:
df1['answer']=df1['answer'].astype(int)

In [145]:
df1

,article_id,start,end,answered,votes,category,title,content,answer
0,21,2017-08-19,2017-11-17,0,9,안전/환경,스텔라 데이지호에 대한 제안입니다.,스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가...,0
1,22,2017-08-19,2017-11-17,0,17,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...,0
2,23,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",0
3,24,2017-08-19,2017-08-26,0,53,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...,0
4,25,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",0
...,...,...,...,...,...,...,...,...,...
395542,517117,2019-02-04,2019-03-06,0,3,보건복지,명절연휴 고속도로 무료반대,명절고속도로 무료보단 대다수의 서민들이 이용하는 대중교통 무료와 명절기간 증차로 했...,0
395543,517119,2019-02-04,2019-03-06,0,23,보건복지,광주사태 가짜 유공자들 정수기로 걸려내야함,광주사태 유공자들 차고 넘치는데 이래 많은 유공자들 그냥놓아두면 재앙이다.\n김대중...,0
395544,517120,2019-02-04,2019-03-06,0,0,안전/환경,환경문제,명절이면 후로 제일문제는 쓰레기 문제 입니다.\n제일문제는 선물세트와 농산물세트 입...,0
395545,517121,2019-02-04,2019-03-06,0,20,정치개혁,"청화대,더불어민주당, 당장 답하라,,,,,,","좌파 더불어민주당, 좌파 정권 청화대는 선한 국민들을 더는 기망하지 말고 담장 답하...",0
395546,517122,2019-02-04,2019-03-06,0,16,인권/성평등,여성부 폐지,국민들이 원합니다\n폐지 좀 시키세요;,0

In [146]:
df1.sort_values(by='answer',ascending=[False])

,article_id,start,end,answered,votes,category,title,content,answer
186976,235102,2018-05-17,2018-06-16,1,201590,인권/성평등,합정 **** 불법 누드촬영,한 유명 유튜버의 사례\n저는 성범죄 피해자입니다. 꼭 한번만 제 이야기를 들어주세...,1
112158,134590,2018-02-08,2018-03-10,1,207772,경제민주화,경제민주화,김상조 공정거래위원장이 경제정의 구현을 위한 정책들에 대해서 적극적인 지지를 보냅...,1
313314,408609,2018-10-17,2018-11-16,0,1192049,안전/환경,강서구 피시방 살인 사건. 또 심신미약 피의자입니다.,2018년 10월 14일 엊그제 일어난 강서구 피시방 살인사건에 대한 청원입니다.\...,1
43992,45581,2017-11-17,2017-12-17,1,281985,보건복지,"권역외상센터 (이국종 교수님) 추가적, 제도적, 환경적, 인력 지원","청원사항)\n중증외상분야의 추가적, 제도적, 환경적, 인력 지원 방안마련\n현 의료...",1
316569,412722,2018-10-20,2018-11-19,0,261418,인권/성평등,조두순의 출소를 반대합니다,제 얘기를 하기에 앞서 요즘 페이스북이라는 sns에서 화제가 되고 있는 글을 하나 ...,1
...,...,...,...,...,...,...,...,...,...
131856,157723,2018-03-04,2018-04-03,0,0,일자리,남양주 청소업체 비정규직 채용의 실태,남양주시 청소업체 비정규직에서 정규직으로 채용하는 과정이 너무 부당...,0
131855,157722,2018-03-04,2018-04-03,0,16,경제민주화,"이명박외 친일재산 환수에 관한 특별법 청원건과 삼성의 구릅의 해체에 관한건,",상기건을 청원합니다,0
131854,157721,2018-03-04,2018-04-03,0,2,일자리,중소기업 직장인들을 위해 개선대책 수립해주세요,중소기업에 다니고 있습니다\n아래 기사가 가슴에 와닿습니다 ㅠ\n수당없고 보너스없고...,0
131853,157720,2018-03-04,2018-04-03,0,14,보건복지,보건소장 의사 임명 금지해주세요,병원의 간호사 1인당 담당환자43명 뉴스\n이것은 보건소가 병원을 감독않고 손을 놓...,0
395546,517122,2019-02-04,2019-03-06,0,16,인권/성평등,여성부 폐지,국민들이 원합니다\n폐지 좀 시키세요;,0

In [147]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395547 entries, 0 to 395546
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   article_id  395547 non-null  int64
 1   start       395547 non-null  object
 2   end         395547 non-null  object
 3   answered    395547 non-null  int64
 4   votes       395547 non-null  int64
 5   category    395547 non-null  object
 6   title       395547 non-null  object
 7   content     395546 non-null  object
 8   answer      395547 non-null  int32
dtypes: int32(1), int64(3), object(5)
memory usage: 25.7+ MB

In [157]:
#아직 답변되지 않은 청원수
df_20.sort_values()

0           0
263687      0
263686      0
263685      0
263684      0
           ..
211483      1
355595      1
320034      1
73197       1
answered    1
Name: votes, Length: 395548, dtype: int64

In [169]:
da=df['answered'].sort_values(ascending=[False])

In [172]:
df[df['answer']==1]['answered'].value_counts()

0    51
1    29
Name: answered, dtype: int64

In [173]:
df['answer_diff']=df['answer']-df['answered']
df

,article_id,start,end,answered,votes,category,title,content,answer,answer_diff
0,21,2017-08-19,2017-11-17,0,9,안전/환경,스텔라 데이지호에 대한 제안입니다.,스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가...,False,0
1,22,2017-08-19,2017-11-17,0,17,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...,False,0
2,23,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",False,0
3,24,2017-08-19,2017-08-26,0,53,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...,False,0
4,25,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",False,0
...,...,...,...,...,...,...,...,...,...,...
395542,517117,2019-02-04,2019-03-06,0,3,보건복지,명절연휴 고속도로 무료반대,명절고속도로 무료보단 대다수의 서민들이 이용하는 대중교통 무료와 명절기간 증차로 했...,False,0
395543,517119,2019-02-04,2019-03-06,0,23,보건복지,광주사태 가짜 유공자들 정수기로 걸려내야함,광주사태 유공자들 차고 넘치는데 이래 많은 유공자들 그냥놓아두면 재앙이다.\n김대중...,False,0
395544,517120,2019-02-04,2019-03-06,0,0,안전/환경,환경문제,명절이면 후로 제일문제는 쓰레기 문제 입니다.\n제일문제는 선물세트와 농산물세트 입...,False,0
395545,517121,2019-02-04,2019-03-06,0,20,정치개혁,"청화대,더불어민주당, 당장 답하라,,,,,,","좌파 더불어민주당, 좌파 정권 청화대는 선한 국민들을 더는 기망하지 말고 담장 답하...",False,0
395546,517122,2019-02-04,2019-03-06,0,16,인권/성평등,여성부 폐지,국민들이 원합니다\n폐지 좀 시키세요;,False,0

In [177]:
df.sort_values('votes',ascending=[False])

,article_id,start,end,answered,votes,category,title,content,answer,answer_diff
313314,408609,2018-10-17,2018-11-16,0,1192049,안전/환경,강서구 피시방 살인 사건. 또 심신미약 피의자입니다.,2018년 10월 14일 엊그제 일어난 강서구 피시방 살인사건에 대한 청원입니다.\...,True,1
208597,269548,2018-06-13,2018-07-13,0,714875,외교/통일/국방,"제주도 불법 난민 신청 문제에 따른 난민법, 무사증 입국, 난민신청허가 폐지/개헌 ...",2012년 난민법 제정으로 인해 외국인은 한달 무비자로 입국할 수 있으나 난민신청자...,True,1
10894,10949,2017-09-06,2017-12-05,1,615354,미래,조두순 출소반대,제발 조두순 재심다시해서 무기징역으로 해야됩니다!!!,True,0
118970,142600,2018-02-19,2018-03-21,1,614127,문화/예술/체육/언론,"김보름, 박지우 선수의 자격박탈과 적폐 빙상연맹의 엄중 처벌을 청원합니다","오늘 여자 단체전 팀추월에서 김보름, 박지우 선수는 팀전인데도 불구하고 개인의 영달...",True,0
183791,230552,2018-05-11,2018-06-10,1,419006,인권/성평등,여성도 대한민국 국민입니다. 성별 관계없는 국가의 보호를 요청합니다.,최근 홍대 누드크로키 모델의 불법촬영 사건이 있었습니다.\n사건은 굉장히 빠르게 처...,True,0
...,...,...,...,...,...,...,...,...,...,...
41072,42536,2017-11-12,2017-12-12,0,0,기타,차기대통령은?,차기대통령은?\n더불어민주당에서는 김경수의원이 나오고 자유한국당은 홍준표가 나오면 ...,False,0
41073,42537,2017-11-12,2017-12-12,0,0,기타,LG SK에 대한 하느님의 귀여운^^ 장난[하느님이 정한 운명을 믿으면 이 글을 보...,LG SK에 대한 하느님의 귀여운^^ 장난[하느님이 정한 운명을 믿으면 이 글을 보...,False,0
41074,42538,2017-11-12,2017-12-12,0,0,미래,★ 국가기술자격증의 희소성이란 대한민국 헌법을 무시하고 오로직 권위주의 사상인 주체...,★ 국가기술자격증의 희소성이란 대한민국 헌법을 무시하고 오로직 권위주의 사상인 주체...,False,0
41077,42542,2017-11-12,2017-12-12,0,0,미래,010-4923-6544 고명숙 54세 입니다,"제발 부탁인데요, 개인적인글 장난글 삼가해 주시고 국가의 문제만 올려주세요, 이렇게...",False,0
197773,253682,2018-05-30,2018-06-29,0,0,행정,대구 몇몇가지 못한 중학교들 수학여행 보내주세요,하나밖에 없는 친구들과의 우정을 보내고 싶습니다,False,0

In [176]:
answered_df_loc=df.loc[df['answer']==1]
answered_df_loc

,article_id,start,end,answered,votes,category,title,content,answer,answer_diff
1752,1785,2017-09-03,2017-11-02,1,296330,인권/성평등,청소년이란 이유로 보호법을 악용하는 잔인무도한 청소년들이 늘어나고있습니다. 반드시 ...,안녕하십니까. 청소년보호법이란 명목하에 나쁜짓을 일삼는 청소년들이 너무나 많아지고 ...,True,0
10894,10949,2017-09-06,2017-12-05,1,615354,미래,조두순 출소반대,제발 조두순 재심다시해서 무기징역으로 해야됩니다!!!,True,0
18111,18278,2017-09-30,2017-10-30,1,235372,인권/성평등,낙태죄 폐지와 자연유산 유도약(미프진) 합법화 및 도입을 부탁드립니다.,안녕하세요. 존경하는 대통령님 의원님\n낙태죄 폐지를 청원합니다.\n현재 대한민국은...,True,0
25032,26024,2017-11-04,2017-12-04,1,216774,안전/환경,'주취감형(술을 먹으면 형벌 감형)' 폐지를 건의(청원)합니다.,"'주취감형'이란, 술을 먹고 범행을 저지를 때, 심신미약 (이성이 없고 우발적)이라...",True,0
43992,45581,2017-11-17,2017-12-17,1,281985,보건복지,"권역외상센터 (이국종 교수님) 추가적, 제도적, 환경적, 인력 지원","청원사항)\n중증외상분야의 추가적, 제도적, 환경적, 인력 지원 방안마련\n현 의료...",True,0
...,...,...,...,...,...,...,...,...,...,...
363005,472309,2018-12-18,2019-01-17,0,269110,인권/성평등,조재범 코치를 강력처벌해주세요,그는 국가대표 심석희 외 다수의 여자선수들을 지속적으로 적어도 14년간 폭행해온 쓰...,True,1
375654,489302,2019-01-07,2019-02-06,0,302856,정치개혁,여.야는 속히 공수처 신설하라 !!!,지금 대한 민국은 나라를 바로 잡기 위해 반드시 이번 정부내에 검찰과 법원의 확실한...,True,1
390787,510422,2019-01-29,2019-02-28,0,312197,기타,"경사 ***, 경장 *** 외 ***에서 뇌물받는지 조사부탁드립니다.","경사 ***, 경장 *** 등등 ***에서 뇌물받는지 조사부탁드립니다.\nㅡㅡㅡㅡㅡ...",True,1
391208,511075,2019-01-29,2019-02-28,0,207784,인권/성평등,"공공연한 여성 대상 약물 범죄 처벌과 ***을 비롯한 클럽, 유흥업소와 경찰 간의 ...",*** 사태의 핵심은 클럽&유흥업소 운영 관리인들의 의도적 약물 사용이 의심되는 납...,True,1
391984,512112,2019-01-30,2019-03-01,0,270999,정치개혁,"시민의 이름으로, 이번 김경수 지사 재판에 관련된 법원 판사 전원의 사퇴를 명령합니다.","촛불혁명으로 세운 정부와 달리, 사법부는 여전히 과거의 구습과 적폐적 습관을 버리지...",True,1

In [180]:
df[df1['answered']==1].value_counts()

AttributeError: 'DataFrame' object has no attribute 'value_counts'

In [195]:
#청원 많이 들어온 분야 순서 3개
df['category'].value_counts()

정치개혁           62750
기타             48682
인권/성평등         34993
안전/환경          30638
교통/건축/국토       28184
외교/통일/국방       26626
육아/교육          25537
보건복지           24848
일자리            23225
행정             20268
문화/예술/체육/언론    18207
미래             18000
경제민주화          16793
성장동력            7253
반려동물            4057
저출산/고령화대책       3584
농산어촌            1902
Name: category, dtype: int64

In [200]:
category=pd.DataFrame(df['category'].value_counts()).reset_index()
category.head(3)

    index  category
0    정치개혁     62750
1      기타     48682
2  인권/성평등     34993

In [202]:
type(category)

pandas.core.frame.DataFrame

In [205]:
category.columns=['category','counts']
category.head(3)

  category  counts
0     정치개혁   62750
1       기타   48682
2   인권/성평등   34993

In [207]:
df

,article_id,start,end,answered,votes,category,title,content,answer,answer_diff
0,21,2017-08-19,2017-11-17,0,9,안전/환경,스텔라 데이지호에 대한 제안입니다.,스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가...,False,0
1,22,2017-08-19,2017-11-17,0,17,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...,False,0
2,23,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",False,0
3,24,2017-08-19,2017-08-26,0,53,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...,False,0
4,25,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",False,0
...,...,...,...,...,...,...,...,...,...,...
395542,517117,2019-02-04,2019-03-06,0,3,보건복지,명절연휴 고속도로 무료반대,명절고속도로 무료보단 대다수의 서민들이 이용하는 대중교통 무료와 명절기간 증차로 했...,False,0
395543,517119,2019-02-04,2019-03-06,0,23,보건복지,광주사태 가짜 유공자들 정수기로 걸려내야함,광주사태 유공자들 차고 넘치는데 이래 많은 유공자들 그냥놓아두면 재앙이다.\n김대중...,False,0
395544,517120,2019-02-04,2019-03-06,0,0,안전/환경,환경문제,명절이면 후로 제일문제는 쓰레기 문제 입니다.\n제일문제는 선물세트와 농산물세트 입...,False,0
395545,517121,2019-02-04,2019-03-06,0,20,정치개혁,"청화대,더불어민주당, 당장 답하라,,,,,,","좌파 더불어민주당, 좌파 정권 청화대는 선한 국민들을 더는 기망하지 말고 담장 답하...",False,0
395546,517122,2019-02-04,2019-03-06,0,16,인권/성평등,여성부 폐지,국민들이 원합니다\n폐지 좀 시키세요;,False,0

In [211]:
df['start'].value_counts()

2017-11-11    9623
2017-09-05    5952
2018-01-11    3368
2018-02-06    2631
2017-11-09    2487
              ...
2017-09-15      74
2017-08-22      69
2017-08-27      49
2017-08-19      39
2017-09-16       4
Name: start, Length: 535, dtype: int64

In [232]:
date=pd.DataFrame(df['start']).reset_index()
date

         index       start
0            0  2017-08-19
1            1  2017-08-19
2            2  2017-08-19
3            3  2017-08-19
4            4  2017-08-19
...        ...         ...
395542  395542  2019-02-04
395543  395543  2019-02-04
395544  395544  2019-02-04
395545  395545  2019-02-04
395546  395546  2019-02-04

[395547 rows x 2 columns]

In [242]:
df['month']=pd.DatetimeIndex(df['start']).month
df['month'].value_counts()

1     52941
11    52847
9     40888
12    38498
10    31687
8     28851
2     28117
7     25714
5     25499
6     25483
4     23227
3     21795
Name: month, dtype: int64

In [244]:
df['year']=pd.DatetimeIndex(df['start']).year
df['year'].value_counts()

2018    299565
2017     72119
2019     23863
Name: year, dtype: int64

In [245]:
df['date']=pd.DatetimeIndex(df['start']).date
df['date'].value_counts()

2017-11-11    9623
2017-09-05    5952
2018-01-11    3368
2018-02-06    2631
2017-11-09    2487
              ...
2017-08-26      74
2017-08-22      69
2017-08-27      49
2017-08-19      39
2017-09-16       4
Name: date, Length: 535, dtype: int64

In [247]:
df['day']=pd.DatetimeIndex(df['start']).day
df['day'].value_counts()

11    22689
5     17307
6     14766
12    13983
24    13461
9     13107
23    13039
22    12868
28    12745
4     12717
18    12679
20    12638
21    12530
30    12524
26    12507
7     12489
8     12297
19    12278
3     12270
17    12185
25    11972
27    11947
13    11938
29    11799
1     11766
2     11730
15    11524
16    11473
10    11412
14    11071
31     7836
Name: day, dtype: int64

In [248]:
df

,article_id,start,end,answered,votes,category,title,content,answer,answer_diff,month,day,year,date
0,21,2017-08-19,2017-11-17,0,9,안전/환경,스텔라 데이지호에 대한 제안입니다.,스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가...,False,0,8,19,2017,2017-08-19
1,22,2017-08-19,2017-11-17,0,17,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...,False,0,8,19,2017,2017-08-19
2,23,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",False,0,8,19,2017,2017-08-19
3,24,2017-08-19,2017-08-26,0,53,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...,False,0,8,19,2017,2017-08-19
4,25,2017-08-19,2017-09-03,0,0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ...",False,0,8,19,2017,2017-08-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395542,517117,2019-02-04,2019-03-06,0,3,보건복지,명절연휴 고속도로 무료반대,명절고속도로 무료보단 대다수의 서민들이 이용하는 대중교통 무료와 명절기간 증차로 했...,False,0,2,4,2019,2019-02-04
395543,517119,2019-02-04,2019-03-06,0,23,보건복지,광주사태 가짜 유공자들 정수기로 걸려내야함,광주사태 유공자들 차고 넘치는데 이래 많은 유공자들 그냥놓아두면 재앙이다.\n김대중...,False,0,2,4,2019,2019-02-04
395544,517120,2019-02-04,2019-03-06,0,0,안전/환경,환경문제,명절이면 후로 제일문제는 쓰레기 문제 입니다.\n제일문제는 선물세트와 농산물세트 입...,False,0,2,4,2019,2019-02-04
395545,517121,2019-02-04,2019-03-06,0,20,정치개혁,"청화대,더불어민주당, 당장 답하라,,,,,,","좌파 더불어민주당, 좌파 정권 청화대는 선한 국민들을 더는 기망하지 말고 담장 답하...",False,0,2,4,2019,2019-02-04
395546,517122,2019-02-04,2019-03-06,0,16,인권/성평등,여성부 폐지,국민들이 원합니다\n폐지 좀 시키세요;,False,0,2,4,2019,2019-02-04

In [252]:
df['week']=pd.DatetimeIndex(df['start']).week
df['week'].value_counts()

45    21750
36    18621
2     14203
3     13650
4     12505
5     10615
47     9955
48     9802
49     9489
50     9096
46     9072
44     8760
51     8607
43     8419
6      8259
8      8141
52     7970
37     7870
22     7595
42     7480
1      7308
26     7256
35     7098
25     7046
34     7043
33     6959
18     6955
38     6820
29     6239
32     6152
16     6146
27     6102
40     6002
41     5904
30     5897
13     5880
15     5778
39     5678
9      5541
14     5340
31     5232
23     5230
28     5203
21     5170
10     4982
12     4835
20     4662
17     4602
19     4305
24     4261
7      4165
11     3897
Name: week, dtype: int64

In [258]:
import re
p=r'.*(돌봄|아이|초등|보육)*'
care=df[df['title'].str.match(p)|
       df['content'].str.match(p,flags=re.MULTILINE)]
care.shape

(395547, 15)